export const district = [
    "Eixample",
    "Sarrià-Sant Gervasi",
    "Les Corts",
    "Ciutat Vella",
    "Sant Martí",
    "Gràcia",
    "La Floresta",
    "Sants-Montjuïc",
    "Port",
    "La Miranda - Ciutat Diagonal",
    "Can Clota",
    "Horta Guinardó",
    "Centre",
    "La Torrasa",
    "Sant Andreu",
    "La Gavarra",
    "La Miranda - Can Candeler",
    "El Gall",
    "La Florida - Les Planes",
    "Les Planes",
    "Nou Barris",
    "Gorg  - Progrés",
    "La Plana - Bellsoleig",
    "Mas Lluí - Els Miralls",
    "La Mina",
    "La Plana - Montesa",
    "Collblanc",
    "Mas Lluí",
    "Fondo",
    "Llefià - Sant Roc - Artigues",
    "La Salut - Lloreda - Sistrells",
    "Santa Eulàlia",
    "Bufalà",
    "La Mallola",
    "El Raval",
    "Can Serra - Pubilla Cases",
    "Finestrelles",
    "Roses - Castellbell",
    "La Catalana",
    "Sant Adriá Nord",
    "Sant Ildefons",
    "Montigalà -Sant Crist",
    "Riera",
    "Fontsanta-Fatjó",
    "El Besós",
    "Singuerlín",
    "Almeda",
    "Santa Rosa - Can Mariner",
    "Bellvitge",
    "Riu",
    "El Pedró",
    "Torreblanca - Pla del Vent",
    "Sant Joan Baptista",
    "Riera Alta - Llatí",
    "Can Sant Joan",
    "Can Vidalet",
    "Casagemes - Canyadó",
    "TV3",
    "Granvia L-H",
];

export const districtOptions = [
    { value: 0, label: "Almeda" },
    { value: 1, label: "Bellvitge" },
    { value: 2, label: "Bufalà" },
    { value: 3, label: "Can Clota" },
    { value: 4, label: "Can Sant Joan" },
    { value: 5, label: "Can Serra - Pubilla Cases" },
    { value: 6, label: "Can Vidalet" },
    { value: 7, label: "Casagemes - Canyadó" },
    { value: 8, label: "Centre" },
    { value: 9, label: "Ciutat Vella" },
    { value: 10, label: "Collblanc" },
    { value: 11, label: "Eixample" },
    { value: 12, label: "El Besós" },
    { value: 13, label: "El Gall" },
    { value: 14, label: "El Pedró" },
    { value: 15, label: "El Raval" },
    { value: 16, label: "Finestrelles" },
    { value: 17, label: "Fondo" },
    { value: 18, label: "Fontsanta-Fatjó" },
    { value: 19, label: "Gorg  - Progrés" },
    { value: 20, label: "Granvia L-H" },
    { value: 21, label: "Gràcia" },
    { value: 22, label: "Horta Guinardó" },
    { value: 23, label: "La Catalana" },
    { value: 24, label: "La Floresta" },
    { value: 25, label: "La Florida - Les Planes" },
    { value: 26, label: "La Gavarra" },
    { value: 27, label: "La Mallola" },
    { value: 28, label: "La Mina" },
    { value: 29, label: "La Miranda - Can Candeler" },
    { value: 30, label: "La Miranda - Ciutat Diagonal" },
    { value: 31, label: "La Plana - Bellsoleig" },
    { value: 32, label: "La Plana - Montesa" },
    { value: 33, label: "La Salut - Lloreda - Sistrells" },
    { value: 34, label: "La Torrasa" },
    { value: 35, label: "Les Corts" },
    { value: 36, label: "Les Planes" },
    { value: 37, label: "Llefià - Sant Roc - Artigues" },
    { value: 38, label: "Mas Lluí" },
    { value: 39, label: "Mas Lluí - Els Miralls" },
    { value: 40, label: "Montigalà -Sant Crist" },
    { value: 41, label: "Nou Barris" },
    { value: 42, label: "Port" },
    { value: 43, label: "Riera" },
    { value: 44, label: "Riera Alta - Llatí" },
    { value: 45, label: "Riu" },
    { value: 46, label: "Roses - Castellbell" },
    { value: 47, label: "Sant Adriá Nord" },
    { value: 48, label: "Sant Andreu" },
    { value: 49, label: "Sant Ildefons" },
    { value: 50, label: "Sant Joan Baptista" },
    { value: 51, label: "Sant Martí" },
    { value: 52, label: "Santa Eulàlia" },
    { value: 53, label: "Santa Rosa - Can Mariner" },
    { value: 54, label: "Sants-Montjuïc" },
    { value: 55, label: "Sarrià-Sant Gervasi" },
    { value: 56, label: "Singuerlín" },
    { value: 57, label: "TV3" },
    { value: 58, label: "Torreblanca - Pla del Vent" },
];

export const municipalitiesOptions = [
    { value: 0, label: "Badalona" },
    { value: 1, label: "Barcelona" },
    { value: 2, label: "Cornellà de Llobregat" },
    { value: 3, label: "El Prat de Llobregat" },
    { value: 4, label: "Esplugues de Llobregat" },
    { value: 5, label: "Hospitalet de Llobregat" },
    { value: 6, label: "Montcada i Reixac" },
    { value: 7, label: "Sant Adriá de Besós" },
    { value: 8, label: "Sant Cugat del Vallès" },
    { value: 9, label: "Sant Feliu de Llobregat" },
    { value: 10, label: "Sant Joan Despí" },
    { value: 11, label: "Sant Just Desvern" },
    { value: 12, label: "Santa Coloma de Gramenet" },
];

export const neighborhoodsOptions = [
    { value: 0, label: "Artigues" },
    { value: 1, label: "Baró de Viver" },
    { value: 2, label: "Bellvitge" },
    { value: 3, label: "Can Baró" },
    { value: 4, label: "Can Peguera - El Turó de la Peira" },
    { value: 5, label: "Can Serra" },
    { value: 6, label: "Canyelles" },
    { value: 7, label: "Casagemes" },
    { value: 8, label: "Centre" },
    { value: 9, label: "Ciutat Meridiana - Torre Baró - Vallbona" },
    { value: 10, label: "Collblanc" },
    { value: 11, label: "Congrés" },
    { value: 12, label: "Diagonal Mar i el Front Marítim del Poblenou" },
    { value: 13, label: "El Baix Guinardó" },
    { value: 14, label: "El Besòs" },
    { value: 15, label: "El Bon Pastor" },
    { value: 16, label: "El Camp d'En Grassot i Gràcia Nova" },
    { value: 17, label: "El Camp de l'Arpa del Clot" },
    { value: 18, label: "El Carmel" },
    { value: 19, label: "El Clot" },
    { value: 20, label: "El Coll" },
    { value: 21, label: "El Congrés i els Indians" },
    { value: 22, label: "El Fort Pienc" },
    { value: 23, label: "El Guinardó" },
    { value: 24, label: "El Gòtic" },
    { value: 25, label: "El Parc i la Llacuna del Poblenou" },
    { value: 26, label: "El Poble Sec - Parc de Montjuïc" },
    { value: 27, label: "El Poblenou" },
    { value: 28, label: "El Putxet i el Farró" },
    { value: 29, label: "El Raval" },
    { value: 30, label: "Gorg" },
    { value: 31, label: "Gran Via L-H" },
    { value: 32, label: "Horta" },
    { value: 33, label: "Hostafrancs" },
    { value: 34, label: "L'Antiga Esquerra de l'Eixample" },
    { value: 35, label: "La Barceloneta" },
    { value: 36, label: "La Bordeta" },
    { value: 37, label: "La Dreta de l'Eixample" },
    { value: 38, label: "La Florida" },
    { value: 39, label: "La Font d'En Fargues" },
    { value: 40, label: "La Font de la Guatlla" },
    { value: 41, label: "La Guineueta" },
    { value: 42, label: "La Marina del Port" },
    { value: 43, label: "La Marina del Prat Vermell" },
    { value: 44, label: "La Maternitat i Sant Ramon" },
    { value: 45, label: "La Nova Esquerra de l'Eixample" },
    { value: 46, label: "La Pau" },
    { value: 47, label: "La Prosperitat" },
    { value: 48, label: "La Sagrada Família" },
    { value: 49, label: "La Sagrera" },
    { value: 50, label: "La Salut" },
    { value: 51, label: "La Teixonera" },
    { value: 52, label: "La Torrasa" },
    { value: 53, label: "La Trinitat Nova" },
    { value: 54, label: "La Trinitat Vella" },
    { value: 55, label: "La Vall d'Hebron - La Clota" },
    { value: 56, label: "La Verneda i la Pau" },
    { value: 57, label: "La Vila Olímpica del Poblenou" },
    { value: 58, label: "Les Corts" },
    { value: 59, label: "Les Planes" },
    { value: 60, label: "Les Roquetes" },
    { value: 61, label: "Les Tres Torres" },
    { value: 62, label: "Llefià" },
    { value: 63, label: "Lloreda" },
    { value: 64, label: "Montigalà" },
    { value: 65, label: "Navas" },
    { value: 66, label: "Pedralbes" },
    { value: 67, label: "Porta" },
    { value: 68, label: "Progrés-Pep Ventura" },
    { value: 69, label: "Provençals del Poblenou" },
    { value: 70, label: "Pubilla Cases" },
    { value: 71, label: "Puigfred" },
    { value: 72, label: "Remei" },
    { value: 73, label: "Sanfeliu" },
    { value: 74, label: "Sant Andreu" },
    { value: 75, label: "Sant Antoni" },
    { value: 76, label: "Sant Crist" },
    { value: 77, label: "Sant Genís Dels Agudells - Montbau" },
    { value: 78, label: "Sant Gervasi - Galvany" },
    { value: 79, label: "Sant Gervasi - La Bonanova" },
    { value: 80, label: "Sant Josep" },
    { value: 81, label: "Sant Martí de Provençals" },
    { value: 82, label: "Sant Pere - Santa Caterina i la Ribera" },
    { value: 83, label: "Sant Roc" },
    { value: 84, label: "Santa Eulàlia" },
    { value: 85, label: "Sants" },
    { value: 86, label: "Sants - Badal" },
    { value: 87, label: "Sarrià" },
    { value: 88, label: "Sistrells" },
    { value: 89, label: "Unknown" },
    { value: 90, label: "Vallcarca i els Penitents" },
    { value: 91, label: "Vallvidrera - El Tibidabo i les Planes" },
    { value: 92, label: "Verdun" },
    { value: 93, label: "Vila de Gràcia" },
    { value: 94, label: "Vilapicina i la Torre Llobeta" },
];

export const propertyTypeOptions = [
    { value: 0, label: "chalet" },
    { value: 1, label: "countryHouse" },
    { value: 2, label: "duplex" },
    { value: 3, label: "flat" },
    { value: 4, label: "penthouse" },
    { value: 5, label: "studio" },
];
